ZSH=$HOME/.oh-my-zsh
ZSH_THEME="philips"
DISABLE_UPDATE_PROMPT="true"
DISABLE_AUTO_UPDATE="true"
DISABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"

# Oh My ZSH plugins
plugins=(bundler gem git rails)

source $ZSH/oh-my-zsh.sh
